export enum NavigationNames {
  MAIN_SCREEN = 'MAIN_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  REG_SCREEN = 'REG_SCREEN',
  ADD_TRANS_SCREEN = 'ADD_TRANS_SCREEN',
  MAIN_NAVIGATOR = 'MAIN_NAVIGATOR',
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
}
